language: bash

services:
  - docker

#
# https://docs.travis-ci.com/user/environment-variables/
#
env:
  - IMAGE_NAME=mingc/android-build-box
  - SOURCE_BRANCH=$TRAVIS_BRANCH
  - SOURCE_COMMIT=$TRAVIS_COMMIT
  - DOCKER_TAG=latest

before_install:
  - env
  # Pull image to use exist layers
  - docker pull mingc/android-build-box
  - docker images

  # Wait 50 minutes to avoid travis timeout.
  # https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
  - travis_wait 50 ./hooks/build

script:
  - docker run -it --rm $IMAGE_NAME flutter --version

after_script:
  - docker images
  - docker inspect $IMAGE_NAME
  - docker rmi $IMAGE_NAME

