name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mingc/android-build-box

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        TAG=$GITHUB_SHA
        docker images
        docker build . \
            --file Dockerfile \
            --tag $IMAGE_NAME:$TAG \
            --cache-from $IMAGE_NAME:latest
        docker images
        docker inspect $IMAGE_NAME:$TAG

    - name: Use docker image
      run: |
        TAG=$GITHUB_SHA
        docker run -it --rm $IMAGE_NAME:$TAG flutter --version
