name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mingc/android-build-box

    steps:
    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: mingc/android-build-box

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Pre build
      run: |
        df -h
        docker images
        docker ps -a
        echo "GITHUB_SHA: $GITHUB_SHA"
        docker image prune -a -f

        # Remove exist images to free disk space
        #docker rmi $(docker images | grep -v IMAGE | awk '{print $3}')
        docker images

        df -h

    # - name: Build the Docker image
    #   run: |
    #     TAG=$GITHUB_SHA
    #     docker build . \
    #         --file Dockerfile \
    #         --tag $IMAGE_NAME:$TAG \
    #         --cache-from $IMAGE_NAME:latest

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: mingc/android-build-box:latest,${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Inspect docker image
      run: |
        TAG=$GITHUB_SHA
        docker images
        docker inspect $IMAGE_NAME:$TAG

    - name: Use docker image
      run: |
        TAG=$GITHUB_SHA
        docker run --rm $IMAGE_NAME:$TAG flutter --version

    - name: Cleanup
      run: |
        TAG=$GITHUB_SHA
        docker rmi $IMAGE_NAME:$TAG
